import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

import {
  isHttpController,
  type AnyHttpController,
  type CatalogTree,
} from "../../utils/index.js";
import {
  filterHttpControllerCatalog,
  type HttpControllerAudienceDefinition,
} from "../audiences/index.js";
import { resolveHttpInputBinding } from "../bindings.js";

export interface HttpClientGenerationOptions {
  /** Complete application HTTP catalog, filtered with the selected audiences. */
  readonly catalog: CatalogTree<AnyHttpController>;
  /** Stable client name used as the prefix for generated TypeScript types. */
  readonly name: string;
  /** Include controllers matching at least one of these audiences. */
  readonly audiences: readonly string[];
  /** Shared vocabulary and defaults used to resolve controller audiences. */
  readonly controllerAudiences: HttpControllerAudienceDefinition;
  /** Generated factory name, such as createAppClient. */
  readonly factoryName: string;
  /** Type-only module containing the source controller catalog. */
  readonly catalogImportPath: string;
  /** Runtime module containing createHttpClientTransport. */
  readonly runtimeImportPath: string;
  /** Export holding the application catalog in catalogImportPath. */
  readonly catalogExportName?: string;
}

export interface WriteHttpClientOptions
  extends HttpClientGenerationOptions {
  readonly outputFile: string;
}

interface CatalogController {
  readonly controller: AnyHttpController;
  readonly path: readonly string[];
}

/** Renders one deterministic, audience-filtered TypeScript HTTP client. */
export function generateHttpClientSource(
  options: HttpClientGenerationOptions,
): string {
  if (options.name.trim() === "") {
    throw new TypeError("The HTTP client generator name cannot be empty.");
  }

  const catalogExportName =
    options.catalogExportName ?? "applicationHttpControllerCatalog";
  const filteredCatalog = filterHttpControllerCatalog(
    options.catalog,
    options.controllerAudiences,
    options.audiences,
  );
  const controllers = collectControllers(filteredCatalog);
  const clientTypeName = toPascalCase(options.name);
  const typeNames = new Set<string>();

  const typeDeclarations = controllers.map(({ controller, path }) => {
    const typeName = `${clientTypeName}${path.map(toPascalCase).join("")}`;

    if (typeNames.has(typeName)) {
      throw new TypeError(
        `Conflicting generated HTTP client type name: ${typeName}.`,
      );
    }

    typeNames.add(typeName);
    const controllerType = renderControllerType(path);

    return [
      `export type ${typeName}Input = input<${controllerType}["inputSchema"]>;`,
      `export type ${typeName}Output = ControllerOutput<${controllerType}>;`,
      `export type ${typeName}OperationId = ${JSON.stringify(controller.operationId)};`,
    ].join("\n");
  }).join("\n\n");
  const clientTree = renderClientBranch(
    filteredCatalog,
    [],
    clientTypeName,
    catalogExportName,
    1,
  );

  return `// This file is generated by ./do generate http-clients. Do not edit it manually.
import type { input, output, ZodType } from "zod";

import type { ${catalogExportName} } from ${JSON.stringify(options.catalogImportPath)};
import {
  createHttpClientTransport,
  type HttpClientOptions,
  type HttpClientOutput,
} from ${JSON.stringify(options.runtimeImportPath)};

type HttpControllerCatalog = typeof ${catalogExportName};
type DefinedControllerOutput<Controller extends { readonly outputSchema?: ZodType }> =
  Extract<Controller["outputSchema"], ZodType>;
type ControllerOutput<Controller extends { readonly outputSchema?: ZodType }> =
  [DefinedControllerOutput<Controller>] extends [never]
    ? void
    : HttpClientOutput<output<DefinedControllerOutput<Controller>>>;

${typeDeclarations}

/** Creates the ${options.name} HTTP client from its generated controller catalog. */
export function ${options.factoryName}(options: HttpClientOptions) {
  const transport = createHttpClientTransport(options);

  return ${clientTree};
}

export type ${clientTypeName}Client = ReturnType<typeof ${options.factoryName}>;
`;
}

/** Writes a generated client only when its deterministic contents changed. */
export async function writeHttpClient(
  options: WriteHttpClientOptions,
): Promise<boolean> {
  const source = generateHttpClientSource(options);
  let currentSource: string | undefined;

  try {
    currentSource = await readFile(options.outputFile, "utf8");
  } catch (error: unknown) {
    if (!isMissingFileError(error)) {
      throw error;
    }
  }

  if (currentSource === source) {
    return false;
  }

  await mkdir(dirname(options.outputFile), { recursive: true });
  await writeFile(options.outputFile, source, "utf8");

  return true;
}

function collectControllers(
  catalog: CatalogTree<AnyHttpController>,
  parentPath: readonly string[] = [],
): readonly CatalogController[] {
  return Object.entries(catalog).flatMap(([name, value]) => {
    const path = [...parentPath, name];

    return isHttpController(value)
      ? [{ controller: value, path }]
      : collectControllers(value, path);
  });
}

function renderClientBranch(
  catalog: CatalogTree<AnyHttpController>,
  parentPath: readonly string[],
  clientTypeName: string,
  catalogExportName: string,
  depth: number,
): string {
  const indentation = "  ".repeat(depth);
  const childIndentation = "  ".repeat(depth + 1);
  const properties = Object.entries(catalog).map(([name, value]) => {
    const path = [...parentPath, name];

    if (!isHttpController(value)) {
      return `${childIndentation}${JSON.stringify(name)}: ${renderClientBranch(
        value,
        path,
        clientTypeName,
        catalogExportName,
        depth + 1,
      )}`;
    }

    const typeName = `${clientTypeName}${path.map(toPascalCase).join("")}`;
    const inputFields = Object.keys(value.inputSchema.shape);
    const inputParameter = inputFields.length === 0
      ? ""
      : `input: ${typeName}Input`;
    const inputArgument = inputFields.length === 0 ? "" : ", input";
    const bindings = inputFields.map((field) => {
      const binding = resolveHttpInputBinding(
        value.route,
        field,
        value.bindings[field],
      );

      return {
        field,
        kind: binding.kind,
        name: binding.name ?? field,
      };
    });
    const serverSymbol = renderServerSymbol(
      catalogExportName,
      path,
    );

    return `${childIndentation}/** Calls {@link ${serverSymbol}} (${value.operationId}). */
${childIndentation}${JSON.stringify(name)}: (${inputParameter}): Promise<${typeName}Output> =>
${childIndentation}  transport.request<${typeName}Output>(${renderOperation(value, bindings, depth + 2)}${inputArgument})`;
  });

  return `{
${properties.join(",\n")}
${indentation}} as const`;
}

function renderOperation(
  controller: AnyHttpController,
  bindings: readonly {
    readonly field: string;
    readonly kind: "body" | "path" | "query";
    readonly name: string;
  }[],
  depth: number,
): string {
  const indentation = "  ".repeat(depth);
  const propertyIndentation = "  ".repeat(depth + 1);
  const closingIndentation = "  ".repeat(depth);
  const renderedBindings = bindings.length === 0
    ? "[]"
    : `[\n${bindings.map((binding) =>
      `${propertyIndentation}  ${JSON.stringify(binding)}`)
      .join(",\n")}\n${propertyIndentation}]`;

  return `{
${propertyIndentation}operationId: ${JSON.stringify(controller.operationId)},
${propertyIndentation}method: ${JSON.stringify(controller.route.method)},
${propertyIndentation}url: ${JSON.stringify(controller.route.url)},
${propertyIndentation}bindings: ${renderedBindings},
${closingIndentation}}`;
}

function renderControllerType(path: readonly string[]): string {
  return `HttpControllerCatalog${path.map((part) =>
    `[${JSON.stringify(part)}]`).join("")}`;
}

function renderServerSymbol(
  root: string,
  path: readonly string[],
): string {
  return path.reduce(
    (symbol, part) => isIdentifier(part)
      ? `${symbol}.${part}`
      : `${symbol}[${JSON.stringify(part)}]`,
    root,
  );
}

function toPascalCase(value: string): string {
  const words = value.match(/[A-Za-z0-9]+/g) ?? [];
  const result = words.map((word) =>
    `${word.charAt(0).toUpperCase()}${word.slice(1)}`)
    .join("");

  if (result === "") {
    throw new TypeError(
      `HTTP client catalog name ${JSON.stringify(value)} cannot form a TypeScript identifier.`,
    );
  }

  return /^[0-9]/.test(result) ? `_${result}` : result;
}

function isIdentifier(value: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value);
}

function isMissingFileError(error: unknown): boolean {
  return error instanceof Error
    && "code" in error
    && error.code === "ENOENT";
}
